Skip to content

Search or jump to…

Pull requests
Issues
Marketplace
Explore

@hanpeaceye
128
4,621 3,291 Huxpro/huxpro.github.io
 Code  Issues 63  Pull requests 9  Projects 1  Wiki  Security  Insights
huxpro.github.io/_config.yml
@Huxpro Huxpro [v1.8] brand new archive and tag
ff66f4a on 25 Sep 2018
@Huxpro @yzgyyang @rpsh @TshuW @Sundrops @LucasIcarus @Kaijun
140 lines (105 sloc)  3.72 KB

# Site settings
title: Hux Blog
SEOTitle: 黄玄的博客 | Hux Blog
header-img: img/home-bg.jpg
email: huxpro@gmail.com
description: "关于程序与设计、黑客与画家 | 黄玄，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @Hux黄玄 的个人博客，与你一起发现更大的世界。"
keyword: "黄玄, Hux黄玄, Hux, 鬼栈, huxpro, @huxpro, 黄玄的博客, Hux Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://huangxuan.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     huxpro
zhihu_username:     huxpro
github_username:    huxpro
twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke 的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "David's Game",
        href: "https://www.ruoyaowu.com/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    }
]
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About




#
# title: Welcome to my blog
# author: Han Peace
# email: hanpeaceyee@daum.net
# description: > # this means to ignore newlines until "show_exerpts:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# show_excerpts: true # set to true to show excerpts on the homepage
#
# # Minima date format
# # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
# sass:
#   sass_dir: _sass
# plainwhite:
#   name: Adam Denisov
#   tagline: Product Owner
#   date_format: "%b %-d, %Y"
#   sitemap: true # set to true to generate sitemap.xml content
#
#   # generate social links in footer
#   social_links:
#     twitter: thelehhman
#     github:  thelehhman
#     linkedIn: in/thelehhman
#     rss: rss
#     # dribbble: jekyll
#     # facebook: jekyll
#     # flickr:   jekyll
#     # instagram: jekyll
#     # linkedin: jekyll
#     # pinterest: jekyll
#     # youtube: jekyll
#     # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
#     # youtube_channel_name: CloudCannon
#     # telegram: jekyll
#     # googleplus: +jekyll
#     # microdotblog: jekyll
#
#     # Mastodon instances
#     # mastodon:
#     # - username: jekyll
#     #   instance: example.com
#     # - username: jekyll2
#     #   instance: example.com
#
# # If you want to link only specific pages in your header, uncomment
# # this and add the path to the pages in order as they should show up
# #header_pages:
# # - about.md
#
# # Build settings
# theme: plainwhite
#
# plugins:
#   - jekyll-seo-tag
# #  - jekyll-feed
