title:            Site Title
description:      Describe your website here.
disqus_shortname:
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:

# Owner/author information
owner:
  name:           Your Name
  avatar:         avatar.jpg
  bio:            "Your bio goes here. It shouldn't be super long but a good sentence or two should suffice."
  email:          you@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      false  # publish future dated posts --  true, false (default)
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp






#
# title: Welcome to my blog
# author: Han Peace
# email: hanpeaceyee@daum.net
# description: > # this means to ignore newlines until "show_exerpts:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# show_excerpts: true # set to true to show excerpts on the homepage
#
# # Minima date format
# # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
# sass:
#   sass_dir: _sass
# plainwhite:
#   name: Adam Denisov
#   tagline: Product Owner
#   date_format: "%b %-d, %Y"
#   sitemap: true # set to true to generate sitemap.xml content
#
#   # generate social links in footer
#   social_links:
#     twitter: thelehhman
#     github:  thelehhman
#     linkedIn: in/thelehhman
#     rss: rss
#     # dribbble: jekyll
#     # facebook: jekyll
#     # flickr:   jekyll
#     # instagram: jekyll
#     # linkedin: jekyll
#     # pinterest: jekyll
#     # youtube: jekyll
#     # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
#     # youtube_channel_name: CloudCannon
#     # telegram: jekyll
#     # googleplus: +jekyll
#     # microdotblog: jekyll
#
#     # Mastodon instances
#     # mastodon:
#     # - username: jekyll
#     #   instance: example.com
#     # - username: jekyll2
#     #   instance: example.com
#
# # If you want to link only specific pages in your header, uncomment
# # this and add the path to the pages in order as they should show up
# #header_pages:
# # - about.md
#
# # Build settings
# theme: plainwhite
#
# plugins:
#   - jekyll-seo-tag
# #  - jekyll-feed
